version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rust-hw"
s3_bucket = "rust-helloworld-lambda"
s3_prefix = "rust-hw"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []