AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Handler: bootstrap
      Architectures: ["x86_64"]
      Runtime: provided.al2
      Timeout: 5
      CodeUri: target/lambda/rust-hw

Outputs:
  FunctionName:
    Value: !Ref HelloWorldFunction
    Description: Name of the Lambda function